write complete task for socket handler
awslabs/aws-c-io pull request #351
Opened 2021-02-03 00:30 UTC by TingDaoK

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-03 19:49 UTC, bretambrose approved these changes

2021-02-04 07:05 UTC, graebm requested changes
Hold off while I try an alternate solution

2021-02-04 07:05 UTC, graebm commented on source/socket_channel_handler.c
> +            struct socket_write_complete_arg arg = {
I'm cooking up an alternate fix in this branch: https://github.com/awslabs/aws-c-io/tree/socket-write-complete

Trying to address the issue down one layer, in `posix/socket.c`.

(`windows/iocp/socket.c` was already doing what we wanted, it never fired the callbacks synchronously. Yay Microsoft!)

2021-02-04 23:58 UTC, graebm commented on source/socket_channel_handler.c
> +            struct socket_write_complete_arg arg = {
alternate fix: https://github.com/awslabs/aws-c-io/pull/353

2021-02-06 00:36 UTC, TingDaoK commented
alternate fix: https://github.com/awslabs/aws-c-io/pull/353

2021-02-06 00:36 UTC, closed without merging